### ISSUE TITLE
Disable common crates

### ISSUE THREAD

**Issue by afonso360** [abaez/ansible-role-rustup#1]
Would it be possible to add a variable to disable installing common crates? or better yet, create a variable that allows you to define which crates to be installed by default?

**Comment by abaez** [comment]
Hey @afonso360 thanks for question. I originally wrote this in a hurry to simply stamp out the crates and targets I tend to use personally, but I have no issue with making a listing for the crates installed by default. 

Expect the change to appear this weekend.

**Comment by abaez** [comment]
Hey @afonso360, 

I went ahead and added the ability to define crates, toolchains, or targets from the `defaults/main.yml` settings. This should make the role more accessible. At the same time, I'm now working on getting `rustup` module for ansible to make this role deprecated in due time. Till then, enjoy the abilities here. 👍
